name: zoned_date
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/tejainece/zoned_date
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  date_format: ^1.0.2

dev_dependencies:
  test: ^0.12.0
